//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class envirexception_rulelog_match
    {
        public long id { get; set; }
        public long envir_id { get; set; }
        public long rule_id { get; set; }
        public int typeid { get; set; }
        public bool isshowed { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
