//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRuleResult
    {
        public long id { get; set; }
        public string pointname { get; set; }
        public string rulename { get; set; }
        public string grouptype { get; set; }
        public string groupsubtype { get; set; }
        public System.DateTime timestamps { get; set; }
        public Nullable<System.DateTime> timestamps2 { get; set; }
        public string description { get; set; }
        public System.DateTime updatetime { get; set; }
        public string cemstype { get; set; }
    }
}
