//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iCEMSDBEntities : DbContext
    {
        public iCEMSDBEntities()
            : base("name=iCEMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalibPoints> CalibPoints { get; set; }
        public virtual DbSet<CalibRecords> CalibRecords { get; set; }
        public virtual DbSet<CalibRuleValue> CalibRuleValue { get; set; }
        public virtual DbSet<chartpointconfig> chartpointconfig { get; set; }
        public virtual DbSet<chartpointconfig_fgd_calib> chartpointconfig_fgd_calib { get; set; }
        public virtual DbSet<chartpointconfig_fgd_launch> chartpointconfig_fgd_launch { get; set; }
        public virtual DbSet<chartpointconfig_fgd_scon> chartpointconfig_fgd_scon { get; set; }
        public virtual DbSet<chartpointconfig_scr_calib> chartpointconfig_scr_calib { get; set; }
        public virtual DbSet<chartpointconfig_scr_launch> chartpointconfig_scr_launch { get; set; }
        public virtual DbSet<chartpointconfig_scr_scon> chartpointconfig_scr_scon { get; set; }
        public virtual DbSet<envirexception_rulelog_match> envirexception_rulelog_match { get; set; }
        public virtual DbSet<EnvirIndicator> EnvirIndicator { get; set; }
        public virtual DbSet<EnvirMonitorData> EnvirMonitorData { get; set; }
        public virtual DbSet<Exception_DayConfirm> Exception_DayConfirm { get; set; }
        public virtual DbSet<Exception_Group> Exception_Group { get; set; }
        public virtual DbSet<exceptiondata_group> exceptiondata_group { get; set; }
        public virtual DbSet<GroupRuleResult> GroupRuleResult { get; set; }
        public virtual DbSet<GroupRuleStatus> GroupRuleStatus { get; set; }
        public virtual DbSet<Indicator_loadpercentage> Indicator_loadpercentage { get; set; }
        public virtual DbSet<LogicRuleAlarmResult> LogicRuleAlarmResult { get; set; }
        public virtual DbSet<MachineCemsInfo> MachineCemsInfo { get; set; }
        public virtual DbSet<MachineShiftSecs> MachineShiftSecs { get; set; }
        public virtual DbSet<moduletypes> moduletypes { get; set; }
        public virtual DbSet<MonthConfig> MonthConfig { get; set; }
        public virtual DbSet<PIAvgRecords> PIAvgRecords { get; set; }
        public virtual DbSet<PIHourAvgPoints> PIHourAvgPoints { get; set; }
        public virtual DbSet<Point_Machine_Map> Point_Machine_Map { get; set; }
        public virtual DbSet<RelevantPoints> RelevantPoints { get; set; }
        public virtual DbSet<reportinfo> reportinfo { get; set; }
        public virtual DbSet<reportrelations> reportrelations { get; set; }
        public virtual DbSet<ReportTypes> ReportTypes { get; set; }
        public virtual DbSet<Rule_Machine_Map> Rule_Machine_Map { get; set; }
        public virtual DbSet<StatisticMetaGroup> StatisticMetaGroup { get; set; }
        public virtual DbSet<SupervisedIndicator> SupervisedIndicator { get; set; }
        public virtual DbSet<t_RulelogS> t_RulelogS { get; set; }
        public virtual DbSet<CEMSRuleLogRecords> CEMSRuleLogRecords { get; set; }
        public virtual DbSet<PlantCemsInfo> PlantCemsInfo { get; set; }
    }
}
