//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineCemsInfo
    {
        public long id { get; set; }
        public Nullable<int> machineid { get; set; }
        public string machinename { get; set; }
        public Nullable<int> plantid { get; set; }
        public Nullable<int> globalmachineid { get; set; }
        public Nullable<System.DateTime> cemstime { get; set; }
        public Nullable<System.DateTime> importedtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> designedload { get; set; }
    }
}
