//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisedIndicator
    {
        public int id { get; set; }
        public int indicatorid { get; set; }
        public string indicatorname { get; set; }
        public Nullable<int> seq2 { get; set; }
    }
}
