//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement2
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RulelogS
    {
        public int ID { get; set; }
        public string RuleName { get; set; }
        public string AlarmLog { get; set; }
        public Nullable<System.DateTime> TimeLog { get; set; }
        public string ShowType { get; set; }
        public string AlarmDis { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> TimeLogEnd { get; set; }
        public Nullable<int> FromXLS { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string CEMStype { get; set; }
        public string ValidatedGroup { get; set; }
        public string ConfirmedGroup { get; set; }
        public Nullable<int> GroupStatus { get; set; }
        public string ConfirmedUser { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public string ValidatedUser { get; set; }
        public Nullable<System.DateTime> ValidatedTime { get; set; }
    }
}
