//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CalibPoints
    {
        public int id { get; set; }
        public string pointname { get; set; }
        public Nullable<int> plantid { get; set; }
        [Required]
        [Range(1, 4)]
        public Nullable<int> machine { get; set; }
    }
}
