//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICEMS_WebManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantCemsInfo
    {
        public long id { get; set; }
        public int plantid { get; set; }
        public string plantname { get; set; }
        public Nullable<int> totalmachines { get; set; }
        public Nullable<int> cemsmachines { get; set; }
        public Nullable<int> importedmachines { get; set; }
        public System.DateTime updatetime { get; set; }
    }
}
